spring.application.name=oauth-assignment

spring.security.oauth2.client.registration.github.client-id=Ov23lip1aCfjMy3r2cR1

spring.security.oauth2.client.registration.github.client-secret=578e6cab5426f9d4e4d7b90694fc7a112176498e
server.port=8080